---
title: "p8109_hw1_jsg2145"
author: "Jared Garfinkel"
date: "2/4/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
pchisq(6, 6)
```

```{r}
dloglikgamma = function(x, a) {return(-log(mean(x)) + log(a) - digamma(a) + mean(log(x)))}
```

```{r}
x = rgamma(20, shape=5, scale = 2)
dloglikgamma(x, 0.1)
dloglikgamma(x, 100)
a= 0.1
b=100
tol = exp(-10)
i = 0
cur = (a+b)/2
res = c(i, cur, dloglikgamma(x, cur))
while (abs(dloglikgamma(x, cur)) > tol) {
  i <- i + 1
  if (dloglikgamma(x, a) * dloglikgamma(x, cur) > 0)
    a <- cur
  else
    b <- cur
  cur <- (a + b) / 2
  res <- rbind(res, c(i, cur, dloglikgamma(x, cur)))
}
```

```{r}
alphahat = res[nrow(res), 2]
betahat = mean(x) / alphahat
res
```

```{r}
d2loglikgamma <- function(x, a) {
  return(1/a - trigamma(a))
}
```

```{r}
cur <- start <- 1
resnewton <- c(i, cur, dloglikgamma(x, cur))
while (abs(dloglikgamma(x, cur)) > tol) {
  i <- i + 1
  cur <- cur - dloglikgamma(x, cur) / d2loglikgamma(x, cur)
  resnewton <- rbind(resnewton, c(i, cur, dloglikgamma(x, cur)))
}

alphahat <- resnewton[nrow(resnewton), 2]
betahat <- mean(x)/alphahat
resnewton
```

